### ISSUE TITLE
Finalize and submit project initiation and the market analysis Report 

### ISSUE THREAD

**Issue by vidhisagathiya** [vidhisagathiya/LearningCompass-Soen6841_Group14#3]
Task:

- Merge the Finaly copies available at [project initiation](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/issues/1) and [market analysis](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/issues/2)
- Make adjustments of extra spaces if needed

**Comment by vidhisagathiya** [comment]
Hi @vidhisagathiya 

Below attached is the final merged Report. Kindly check and make a submission.
[Report_SOEN 6841_Group _14.pdf](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/files/14234986/Report_SOEN.6841_Group._14.pdf)
 
 Thank you

**Comment by anuragagarwal6895** [comment]
Hi @vidhisagathiya

Below attached is the final merged Report. Kindly check and make a submission.
[Report_SOEN 6841_Group _14.pdf](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/files/14234986/Report_SOEN.6841_Group._14.pdf)

Thank you
