### ISSUE TITLE
Creation of Feasibility Analysis report

### ISSUE THREAD

**Issue by anuragagarwal6895** [vidhisagathiya/LearningCompass-Soen6841_Group14#5]
This issue has been created to monitor progress in information gathered for Feasibility Study report.

**Comment by aksharpatel17** [comment]
Hello @anuragagarwal6895, I have added Feasibility Analysis part in the Report. Please check it.

[Project Report - SOEN 6841 - Group 14.pdf](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/files/14949913/Project.Report.-.SOEN.6841.-.Group.14.pdf)

**Comment by anuragagarwal6895** [comment]
Hello @aksharpatel17 

Thank you for your inputs. Looks good to me. Hence, closing the issue.

Thanks!
