### ISSUE TITLE
Creation of Solution proposal report

### ISSUE THREAD

**Issue by anuragagarwal6895** [vidhisagathiya/LearningCompass-Soen6841_Group14#6]
This issue has been created to track progress in the solution proposal part of the project requirement.

**Comment by salu2303** [comment]
Hello, I am attaching my PDF till market analysis. Now, @aksharpatel17  you can start working on the next topic which is Feasibility Analysis.
[Uploading market_Project Report - SOEN 6841 - Group 14.pdf…]()
