### ISSUE TITLE
Creation of Final Project Budget

### ISSUE THREAD

**Issue by anuragagarwal6895** [vidhisagathiya/LearningCompass-Soen6841_Group14#7]
This issue is created to track and record Budget of the Learning Compass project.

**Comment by vidhisagathiya** [comment]
Hello @anuragagarwal6895 

I have added the budget analysis in the final report draft. Kindly, check and proceed with the next steps.

[Final Report - SOEN 6841 - Group 14.pdf](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/files/14950174/Final.Report.-.SOEN.6841.-.Group.14.pdf)


Thanks!
