### ISSUE TITLE
Final Project Presentation

### ISSUE THREAD

**Issue by anuragagarwal6895** [vidhisagathiya/LearningCompass-Soen6841_Group14#8]
To track the progress of final powerpoint presentation.

**Comment by salu2303** [comment]
I am attaching the PDF which includes information till Market Value Analysis. @aksharpatel17 you can start working on the Feasibility Analysis.
[Uploading market_Project Report - SOEN 6841 - Group 14.pdf…]()

**Comment by anuragagarwal6895** [comment]
@Team, (@aksharpatel17, @salu2303, @vidhisagathiya)

Requesting you to please upload the final powerpoint presentation to the repository.
Once done kindly add a note and i will mark the issue as completed.

Let me know if any concerns!

Thanks!

**Comment by aksharpatel17** [comment]
Here is final presentation report @anuragagarwal6895 
[Group_14_SPM.pdf](https://github.com/vidhisagathiya/LearningCompass-Soen6841_Group14/files/14950300/Group_14_SPM.pdf)

Please close the issue.
Thank you 🙏

**Comment by anuragagarwal6895** [comment]
Closing the issue. Thanks!
